### ISSUE TITLE
STL Datasets

### ISSUE THREAD

**Issue by baqwas** [The-Loony-Squad/PowerPlay-Claw#1]
Hello,

Encountering _newbie_ issues with the STL files - **not a PowerPlay Claw issue** but rather a lack of knowledge about STL and Blender.

The local public library experienced difficulty in printing the STL (e.g. servo mount) as provided directly with the file from this site. The operator reported errors in processing the file.

I imported the same original file into Blender but saw no visualization issue. I re-exported this file to STL format  and sent it to the library. The feedback this time was the dimensions of the file were minuscule. I changed Units in Blender prior to import from the default to metric (mm, gm).

Second time around, I changed the Units in Blender to imperial (in, oz) prior to the import. I performed a Measure operation. The width was reported as ~11 inches.

I am not familiar with the intrinsic units in the STL file at the site. I really don't want (or need) to use Blender. I simply want some reassurance that the file that I send to the library for 3D printing will retain the original dimensions. What is the _best practice_ to avoid the processing errors (in all the STL files from this site that I sent to the library). Thanks.

Regards.

P.S.
The library regularly prints STL files exported from OnShape or Blender by yours truly.

**Comment by The-Loony-Squad** [comment]
So sorry you're having issues! The best practice would be to export the
files directly from onshape. Here is the document:
https://cad.onshape.com/documents/129dc57b75a629234258d945/w/393048bd49f90455ff9c0a22/e/25850ec320968eb5a49b6b94.
You will want to go through the CAD or the Master Assembly Instructions
document to decide which version best fits your robot. Hopefully this
solves your problem!

Out of curiosity and concern for others trying to use the design, was it just the servo mount that caused issues or was it all of the files?

Thanks,
Jameson

**Comment by The-Loony-Squad** [comment]
As a follow-up, I just downloaded the repository as it is uploaded and opened each of the files in Cura. All of the dimensions and scaling are correct. There are a few parts that may need to be turned to the correct printing orientation, but that should not be an issue (although I'm about to update all the files to make sure they are in the correct orientation just for ease of access). All of the files are exported from Onshape and then uploaded here, so it would be strange if exporting them again solves the issue. I'll be curious to hear how it goes.

**Comment by baqwas** [comment]
Thanks! I agree with you that it is strange because I bet that the library is using Cura! The only coincidence was the Blender connection. Sufyan wants the camera and sensor on the mount; now that you have done the work for us, using Blender for intermediate changes is moot.

Yes, I've given the library only the _original_ servo mount part directly from your OnShape drawing as a test case. I'll await the feedback from the Librarian (who reviews the files).

Regards.

**Comment by baqwas** [comment]
> Out of curiosity and concern for others trying to use the design, was it just the servo mount that caused issues or was it all of the files?

The Librarian mentioned ALL files which confused me because I had included a standard OnShape export STL file too where there should've have been no ambiguity about the units. Don't worry about this any further. I'll provide full feedback once all the parts are printed. Thanks again.

Regards.

**Comment by baqwas** [comment]
Hello,

Removing the "import faulty parts" option took care of the issue at our end. We ignored _outer race_ too. Everything is fine. Used Cura to confirm. If the library (where the printing is done) complains again, I'll offer a screen shot. Perhaps I should get their printer model too while I'm at it.

Once again, many, many thanks for your work on this important component for POWERPLAY.

Regards.

**Comment by The-Loony-Squad** [comment]
I'm glad that worked!

Happy to!
